name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22.0.1'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/academetrics/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install dependencies
        run: mvn -f academetrics/pom.xml install -DskipTests

      - name: Run tests
        run: mvn -f academetrics/pom.xml test | tee test-results.txt
        continue-on-error: true

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test-results.txt

      - name: Display test failures
        if: ${{ failure() }}
        run: tail -n 100 test-results.txt
